alert('Boas-vindas ao sistema de RH! Vamos fazer seu cadastro!')

let nome = prompt('Qual seu nome completo?')
const dataNascimento = prompt('Qual sua data de nascimento? (dd/mm/aaaa)')
let endereco = prompt('Qual seu endereço? Rua, nº, Bairro')
const cpf = Number(prompt('Qual seu CPF? 12345678910'))
let escolaridade = prompt('Qual sua escolaridade?')
const cnh = prompt('Possui CNH? Sim/Não')
let filhos = Number(prompt('Possui filhos/filhas? Se sim, quqantos?'))
let cargo = prompt('Qual seu cargo atual?')
let salario = Number(prompt('Qual seu salário? (0000)'))
let comissao = confirm('Você recebe comissão? Se sim, aperte em confirme, caso não, clique em cancel')
let admissao = Number(prompt('Qual seu ano de admissão?'))

console.log(typeof nome)
console.log(typeof dataNascimento)
console.log(typeof endereco)
console.log(typeof cpf)
console.log(typeof escolaridade)
console.log(typeof cnh)
console.log(typeof filhos)
console.log(typeof cargo)
console.log(typeof salario)
console.log(typeof comissao)
console.log(typeof admissao)

console.log('Nome:', nome)
console.log('Data de nascimento:', dataNascimento)
console.log('Endereço:', endereco)
console.log('Nº CPF:', cpf)
console.log('Escolaridade:', escolaridade)
console.log('Possui CNH:', cnh)
console.log('Possui filhos:', filhos)
console.log('Cargo atual:', cargo)
console.log('Salário atual:', salario)
console.log('Recebe comissão:', comissao)
console.log('Ano de Admissão:', admissao)